services:
  postgres:
    image: postgres:16-alpine
    container_name: brasux-auth-postgres
    restart: always
    environment:
      POSTGRES_USER: brasux_user
      POSTGRES_PASSWORD: Brasux@2026
      POSTGRES_DB: brasux_auth_db
    ports:
      - "5434:5432"
    volumes:
      - brasux_auth_pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: brasux-auth-api
    restart: always
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: "postgresql://brasux_user:Brasux%402026@postgres:5432/brasux_auth_db"
      JWT_SECRET: "brasux_auth_super_secret_prod"
      JWT_EXPIRES_IN: "15m"
      PORT: 3333
      NODE_ENV: "production"

volumes:
  brasux_auth_pgdata: